friendly_subject_names = {
    "Homegroup": "Homegroup",
    "Art": "Art",
    "ComL": "ComLife",
    "Community Life": "ComLife",
    "Dram": "Drama",
    "Elec": "Electronics",
    "Eng": "English",
    "Farm": "Farming",
    "Huma": "Humanities",
    "Food": "Food Tech",
    "Germ": "German",
    "Math": "Maths",
    "Medi": "Media",
    "Musi": "Music",
    "OuEd": "Outdoor Ed",
    "Outdoor Edu": "Outdoor Ed",
    "PE": "PE",
    "Research": "Research Science",
    "RS": "Research Science",
    "Sci": "Science",
    "Sport": "Sport",
    "Vis": "VisCom",
    "Commerce": "Commerce",
    "Comm": "Commerce",
}